version: '3'

volumes:
  static:
  media_value:
  db_data:
  redoc:

services:
  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - .env

  frontend:
    image: remaiddd/foodgram-frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - db
    env_file:
      - .env

  backend:
    image: remaiddd/foodgram-backend
    volumes:
      - static:/backend_static
      - media_value:/media/
      - redoc:/api/docs/
    depends_on:
      - frontend
    env_file:
      - .env

  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - static:/staticfiles/
      - media_value:/media/
      - redoc:/api/docs/
    env_file:
      - .env
    depends_on:
      - backend
