volumes:
  postgres_data:
  static_value:
  media_value:
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  backend:
    image: remaiddd/foodgram_backend:latest
    env_file: .env
    volumes:
      - static_value:/backend_static
      - media_value:/app/media/
  frontend:
    env_file: .env
    image: remaiddd/foodgram_frontend:latest
    volumes:
      - static_value:/app/result_build/build
  nginx:
    image: remaiddd/foodgram_gateaway:latest
    ports:
      - "8000:80"
    env_file: .env
    volumes:
      - static_value:/static/
      - media_value:/media/