USER_USERNAME_MAX = 150
USER_EMAIL_MAX = 150
USER_PASSWORD_MAX = 120
USER_FIRST_NAME_MAX = 100
USER_SECOND_NAME_MAX = 100
USER_AVATAR_UPLOAD_TO = 'users/'
USER_USERNAME_REGEX = r'(?!me\b)(^[\w.@+-]+\Z)'

RECIPE_NAME_MAX = 15
RECIPE_COOKING_TIME_MIN = 1
RECIPE_IMAGE_UPLOAD_TO = 'recipes/'

INGRIDIENT_NAME_MAX = 15
INGREDIENT_INLINE_MIN_AMOUNT = 1
INGREDIENT_MEASUREMENT_UNIT_MAX_LENGTH = 100
INGREDIENT_MIN_AMOUNT = 1

DEFAULT_PAGE_SIZE = 6
